name: Desplegar Aplicacion

on:
  push:
    branches:
      - main
      - testing

jobs:
  deploy-testing:
    if: github.ref == 'refs/heads/testing'
    runs-on: ubuntu-latest

    steps:
      - name: Conectar y desplegar en test.rgentradas.com
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            . /home/rgentradas-deployer/.bashrc && /home/rgentradas-deployer/deploy.sh testr2002 testing test.rgentradas.com

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Conectar y desplegar en rgentradas.com
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          
          script: |
            . /home/rgentradas-deployer/.bashrc && /home/rgentradas-deployer/deploy.sh rgent6815 main rgentradas.com